# NOTE: This workflow expects that branch protection rules require all checks to pass before merging.
# Auto-merge will only occur if all required status checks and reviews are successful.

# INFO: This is deactivated temporarily till final decision with Renovate is made.

# name: Dependabot auto-approve and auto-merge
on:
    repository_dispatch: 
#   pull_request:
#     types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    name: Auto-approve and auto-merge Dependabot PRs
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'AbsaOSS/generate-release-notes'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@300ce8ecb06a0ee68a73f5f4f6d03c034c623e53
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Enable auto-merge for Dependabot PRs
        if: startsWith(steps.metadata.outputs.update-type, 'version-update') || startsWith(steps.metadata.outputs.update-type, 'security')
        run: gh pr merge --auto --squash "$PR_URL"
        continue-on-error: true
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
